# Generated by Django 4.2.6 on 2023-12-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='level',
            field=models.CharField(choices=[('1', 'Łatwy'), ('2', 'Średni'), ('3', 'Zaawansowany')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipesolver.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipesolver.difficultylevel'),
        ),
    ]
