# Generated by Django 4.2.6 on 2023-12-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesolver', '0004_alter_recipe_category_alter_recipe_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipesolver.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipesolver.difficultylevel'),
        ),
    ]
